apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: demo-wp
  labels:
    app: wordpress
spec:
  nodeName: workernode01
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: mariadb:10.5.12-focal
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: onlyDevelopment
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
