apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: demo-wp
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 80
    protocol: TCP
  selector:
    app: wordpress
