apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
  namespace: demo-apps
  labels:
    app: demo-nginx
spec:
  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 80
    protocol: TCP
  selector:
    app: demo-nginx